### ISSUE TITLE
Ambiguous character forms 0 and 1 should be accepted for O and I during decode

### ISSUE THREAD

**Issue by JasonKleban** [emn178/hi-base32#3]
One of the intentions of base32 is that ambiguous characters are avoided for when a human needs to transfer or communicate a value.  If the human guesses wrong among the ambiguous character forms, the decode will fail.  This simple change, adding `'1': 8` and `'0': 14` should address that, right?

```
  var BASE32_DECODE_CHAR = {
    'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, '1': 8,
    'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, '0': 14, 'P': 15, 'Q': 16, 
    'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 
    'Z': 25, '2': 26, '3': 27, '4': 28, '5': 29, '6': 30, '7': 31
  };
```

**Comment by emn178** [comment]
https://en.wikipedia.org/wiki/Base32#RFC_4648_Base32_alphabet

> It uses an alphabet of A–Z, followed by 2–7. 0 and 1 are skipped due to their similarity with the letters O and I.

It has considered that. And it's a standard, we can't change it.
