### ISSUE TITLE
.decode.asBytes() is confused by spaces and lowercase

### ISSUE THREAD

**Issue by mk-pmb** [emn178/hi-base32#8]
From [RFC 3548](https://tools.ietf.org/html/rfc3548):

> Implementations MUST reject the encoding if it contains characters
> outside the base alphabet when interpreting base encoded data,
> — section 2.3

so the decoder should have failed loudly when I added the spaces, instead of giving a strange result.
When I re-encode the strange result, the encoded version has "A" in all the places where the original input had space or lowercase characters. The latter is especially surprising because (emphasis mine):

> The Base 32 encoding is designed to represent […]
> octets in a form that __needs to be case insensitive__
> — section 5

```javascript
var hex = a => a.map(b => ('0' + b.toString(16)).slice(-2)).join(' ')
hex(base32.decode.asBytes('UEE7DYSQG46JSVHPFUWIQTRYME4QCWXJ'))
"a1 09 f1 e2 50 37 3c 99 54 ef 2d 2c 88 4e 38 61 39 01 5a e9"
hex(base32.decode.asBytes('UEE7 DYSQ G46J SVHP FUWI QTRY ME4Q CWXJ'))
"a1 09 f0 0f 12 80 0d cf 24 12 a9 de 02 d2 c8 04 27 1c 01 84 e4 00 2b 5d"
hex(base32.decode.asBytes('uee7 dysq g46j svhp fuwi qtry me4q cwxj'))
"00 01 f0 00 00 00 01 cf 00 00 00 00 00 00 00 00 00 00 00 00 e0 00 00 00"
hex(base32.decode.asBytes('uee7dysqg46jsvhpfuwiqtryme4qcwxj'))
"00 01 f0 00 00 07 3c 00 00 00 00 00 00 00 00 00 38 00 00 00"
```

**Comment by emn178** [comment]
it will throw error in v0.5.0

**Comment by mk-pmb** [comment]
Thanks! :+1:
